#!/bin/bash

set -euo pipefail
cd "$(dirname "$0")"

say() { echo "$@" >&2; }
say_do() { say "$@"; "$@"; }

say_do sudo rm -rf rootfs

say_do sudo debootstrap --no-check-gpg --arch=i386 --variant=minbase \
    lenny rootfs http://debian.snt.utwente.nl/debian-archive/debian

say_do sudo tar c -C rootfs . | pv -N import | docker import - kiboit/debian-lenny
